<?php

namespace IKNSA\BlogBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsByPostId($post)
    {
        return $this->getEntityManager()
                    ->createQuery(
                        "SELECT c.id, c.comment, c.createdAt, cu.username FROM IKNSABlogBundle:Comment c JOIN c.user cu JOIN c.post p WHERE p = $post ORDER BY c.id DESC"
                    )
                    ->getResult();
    }
}
